# Serve launch configuration for pubspec.yaml.
type: serve
path: pubspec.yaml

serve:
  # Additional args for pub serve
  args:
    # Mode to run transformers in. (defaults to "debug")
    #mode: debug
    # Use all default source directories.
    #all: true
    # The JavaScript compiler to use to build the app. [dart2js, dartdevc, none]
    #web-compiler: dartdevc
    # Defines an environment constant for dart2js.
    #define: variable=value[,variable=value]
    # The hostname to listen on. (defaults to "localhost")
    #hostname: localhost
    # The base port to listen on. (defaults to "8084")
    port: 8084
    # Force the use of a polling filesystem watcher.
    #force-poll: true
    #no-force-poll: true
